on: [push, pull_request]
name: Build and Test check
jobs:
  check:
    name: cargo-check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv6m-none-eabi
          override: true
          profile: minimal
      - uses: actions-rs/cargo@v1
        with:
          command: build
